name: Sync v1 tag
on:
  release:
    types: [published]

jobs:
  sync-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v1.')
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for all tags

      - name: Sync v1 tag
        run: |
          git tag -d v1 || true
          git tag v1 ${{ github.ref_name }}  # Link v1 tag to the new v1.x.y tag
          git push origin v1 --force-with-lease
